image: "python:3.7"

default:
  tags:
    - docker

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

flake8:
  stage: Static Analysis
  script:
  - pip install flake8
  - flake8 --max-line-length=120 nextcloud_cal.py

pylint:
  stage: Static Analysis
  allow_failure: true
  script:
  - pip install pylint
  - pylint -d C0301,C0103 nextcloud_cal.py

unit_test:
  stage: Test
  script:
  - pwd
  - ls -l
  - export PYTHONPATH="$PYTHONPATH:."
  - python -c "import sys;print(sys.path)"
  - pip install pytest
  - pytest
