---
name: Test Python ncalcli
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.x' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

      - run: pip install -r requirements.txt
      - run: pip install flake8 pylint pytest
      - run: flake8 --max-line-length=120 nextcloud_cal.py
      - run: pylint -d C0301,C0103 nextcloud_cal.py || true
      - run: pytest
